name: Deploy App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  ECR_HOST_URL: ${{ secrets.AWS_ACCOUNT_NUMBER }}.dkr.ecr.${{ secrets.AWS_ECR_REGION }}.amazonaws.com
  ECR_REPOSITORY_URL: ${{ secrets.AWS_ACCOUNT_NUMBER }}.dkr.ecr.${{ secrets.AWS_ECR_REGION }}.amazonaws.com/${{ secrets.AWS_ECR_REPOSITORY }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: FE - Install Deps
        run: cd frontend && npm i

      - name: FE - Build
        run: cd frontend && npm run build:prod

      - name: SSH test
        uses: rajpal-se/configure-ssh-credentials
        with:
          hostname: ${{ secrets.VPS_IP_ADDRESS }}
          key: ${{ secrets.VPS_USER_SSH_KEY }}

      - name: BE - Install Deps
        run: cd backend && npm i

      - name: Setup FE
        run: cp -r frontend/build/* backend/public

      - name: Build Docker image
        run: docker build -f backend/Dockerfile -t ${{ env.ECR_REPOSITORY_URL }}:latest backend

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_ECR_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Push Docker image to AWS ECR
        run: docker push ${{ env.ECR_REPOSITORY_URL }}:latest

      # SSH into the VPS, Pull the Image, and Run the Container
      - name: Set up SSH keys for VPS
        run: |
          mkdir -p ./.tmp/.ssh
          echo "${{ secrets.VPS_USER_SSH_KEY }}" > ./.tmp/.ssh/github-actions
          chmod 600 ./.tmp/.ssh/github-actions

      - name: SSH into VPS and Deploy Docker Container
        env:
          VPS_IP: ${{ secrets.VPS_IP_ADDRESS }}
          VPS_USER: ${{ secrets.VPS_USER }}
        run: |
          ssh -q -i ./.tmp/.ssh/github-actions -o StrictHostKeyChecking=no ${{ env.VPS_USER }}@${{ env.VPS_IP }} << 'EOF'
            clear
            aws ecr get-login-password --region ${{ secrets.AWS_ECR_REGION }} | docker login --username AWS --password-stdin ${{ env.ECR_HOST_URL }}

            docker pull ${{ env.ECR_REPOSITORY_URL }}:latest

            docker stop ${{ secrets.APP_CONTAINER_NAME }} 2> /dev/null
            docker rm ${{ secrets.APP_CONTAINER_NAME }} 2> /dev/null

            docker run -d --name ${{ secrets.APP_CONTAINER_NAME }} -p ${{ secrets.APP_PORT_MAPPING }} --network vps ${{ env.ECR_REPOSITORY_URL }}:latest
          EOF

      # Remove local dangling Docker images
      - name: Remove dangling Docker images locally
        run: |
          docker image prune -f

      # Remove dangling Docker images from AWS ECR
      - name: Remove dangling Docker images from ECR
        run: |
          for digest in $(aws ecr describe-images --repository-name ${{ secrets.AWS_ECR_REPOSITORY }} --query 'imageDetails[?imageTags==`null`].imageDigest' --output text); do
            aws ecr batch-delete-image --repository-name ${{ secrets.AWS_ECR_REPOSITORY }} --image-ids imageDigest=$digest
          done
